- hosts: localhost

  tasks:
    - name: Install inter font
      become: yes
      kewlfft.aur.aur:
        name: ttf-inter
    - name: Set GTK dark theme
      community.general.dconf:
          key: /org/gnome/desktop/interface/color-scheme
          value: "'prefer-dark'"
    - name: Set GTK font to Inter
      ansible.builtin.dconf:
        key: /org/gnome/desktop/interface/font-name
        value: "'Inter Variable 11'"
    - name: Create GTK 3.0 configuration directory if it does not exist
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.config/gtk-3.0"
        state: directory
    - name: Check if GTK 3.0 configuration file exists
      ansible.builtin.stat:
        path: "{{ ansible_env.HOME }}/.config/gtk-3.0/settings.ini"
      register: gtk_settings_file
    - name: Create settings.ini file with dark theme configuration if it does not exist
      ansible.builtin.copy:
        dest: "{{ ansible_env.HOME }}/.config/gtk-3.0/settings.ini"
        content: |
          [Settings]
          gtk-application-prefer-dark-theme = true
      when: not gtk_settings_file.stat.exists
