- hosts: localhost

  tasks:
    - name: Install packages
      become: yes
      community.general.pacman:
        name:
          - hyprland
          - kitty
          - rofi-wayland
          - waybar
          - xdg-user-dirs
          - xdg-desktop-portal-gtk
          - xdg-desktop-portal-hyprland
    - name: Create home folder folders
      ansible.builtin.command: xdg-user-dirs-update
    - name: Clone dotfiles
      git:
        repo: https://github.com/warbacon/dotfiles
        dest: /tmp/dotfiles
    - name: Apply hypr config
      ansible.builtin.copy:
        dest: "{{ ansible_env.HOME }}/.config"
        src: "/tmp/dotfiles/config/hypr"
    - name: Apply waybar config
      ansible.builtin.copy:
        dest: "{{ ansible_env.HOME }}/.config"
        src: "/tmp/dotfiles/config/waybar"
