---
- hosts: localhost
  tasks:
    - name: Install packages
      become: true
      community.general.pacman:
        name: 
          - curl
          - fd
          - neovim
          - nodejs-lts-iron
          - npm
          - python
          - ripgrep
          - ttf-nerd-fonts-symbols
          - unzip
          - wget
          - wl-clipboard
    - name: Clone Neovim config
      ansible.builtin.git:
        repo: https://github.com/warbacon/nvim-config
        dest: "{{ ansible_env.HOME }}/.config/nvim"
