- hosts: localhost

  tasks:
    community.general.pacman:
      name:
        - curl
        - diff-so-fancy
        - eza
        - fd
        - ffmpeg
        - fish
        - fzf
        - git
        - imagemagick
        - jq
        - lazygit
        - p7zip
        - ripgrep
        - starship
        - trash-cli
        - wget
