---
- hosts: localhost

  tasks:
    - name: Install AMDGPU packages
      become: true
      community.general.pacman:
        name:
          - mesa
          - rocm-smi-lib
          - vulkan-radeon
