---
- hosts: localhost

  tasks:
    - name: Install gtk3
      become: true
      community.general.pacman:
        name:
          - gtk3
    - name: Install inter font
      kewlfft.aur.aur:
        name: ttf-inter
    - name: Set GTK dark theme
      ansible.builtin.command: gsettings set org.gnome.desktop.interface color-scheme prefer-dark
    - name: Set GTK font to Inter
      ansible.builtin.command: gsettings set org.gnome.desktop.interface font-name 'Inter Variable 11'
    - name: Create GTK 3.0 configuration directory if it does not exist
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.config/gtk-3.0"
        state: directory
    - name: Check if GTK 3.0 configuration file exists
      ansible.builtin.stat:
        path: "{{ ansible_env.HOME }}/.config/gtk-3.0/settings.ini"
      register: gtk_settings_file
    - name: Create settings.ini file with dark theme configuration if it does not exist
      ansible.builtin.copy:
        dest: "{{ ansible_env.HOME }}/.config/gtk-3.0/settings.ini"
        content: |
          [Settings]
          gtk-application-prefer-dark-theme = true
      when: not gtk_settings_file.stat.exists
