---
- hosts: localhost

  tasks:
    - name: Install packages
      become: true
      community.general.pacman:
        name:
          - brightnessctl
          - dunst
          - grim
          - gtk3
          - hypridle
          - hyprland
          - hyprlock
          - hyprpaper
          - imv
          - kitty
          - libcanberra
          - pulsemixer
          - rofi-wayland
          - rofimoji
          - slurp
          - waybar
          - wtype
          - xdg-desktop-portal-gtk
          - xdg-desktop-portal-hyprland
          - xdg-user-dirs
          - yazi
    - name: Create home folder folders
      ansible.builtin.command: xdg-user-dirs-update
    - name: Clone dotfiles
      git:
        repo: https://github.com/warbacon/dotfiles
        dest: /tmp/dotfiles
    - name: Apply hypr config
      ansible.builtin.copy:
        dest: "{{ ansible_env.HOME }}/.config"
        src: "/tmp/dotfiles/config/hypr"
    - name: Apply waybar config
      ansible.builtin.copy:
        dest: "{{ ansible_env.HOME }}/.config"
        src: "/tmp/dotfiles/config/waybar"
    - name: Apply dunst config
      ansible.builtin.copy:
        dest: "{{ ansible_env.HOME }}/.config"
        src: "/tmp/dotfiles/config/dunst"
    - name: Apply rofi config
      ansible.builtin.copy:
        dest: "{{ ansible_env.HOME }}/.config"
        src: "/tmp/dotfiles/config/rofi"
    - name: Hide GTK titlebar buttons
      ansible.builtin.command: gsettings set org.gnome.desktop.wm.preferences button-layout ''
