---
- hosts: localhost
  name: Playbook principal

- name: Install paru
  ansible.builtin.import_playbook: paru.yml
- name: Install AMDGPU packages
  ansible.builtin.import_playbook: amd.yml
- name: Setup hyprland
  ansible.builtin.import_playbook: hyprland.yml
- name: Setup gtk
  ansible.builtin.import_playbook: gtk.yml
- name: Install tools
  ansible.builtin.import_playbook: tools.yml
- name: Install and setup Neovim
  ansible.builtin.import_playbook: neovim.yml
