---
- hosts: localhost

  tasks:
    - name: Install qt5ct and qt6ct
      become: true
      community.general.pacman:
        name:
          - qt5ct
          - qt6ct
    - name: Install breeze icons
      become: true
      community.general.pacman:
        name:
          - breeze-icons
    - name: Clone dotfiles
      git:
        repo: https://github.com/warbacon/dotfiles
        dest: /tmp/dotfiles
    - name: Apply qt5ct config
      ansible.builtin.copy:
        dest: "{{ ansible_env.HOME }}/.config"
        src: "/tmp/dotfiles/config/qt5ct"
    - name: Apply qt6ct config
      ansible.builtin.copy:
        dest: "{{ ansible_env.HOME }}/.config"
        src: "/tmp/dotfiles/config/qt6ct"
